#pragma config(Sensor, dgtl3,  limitSwitchTop, sensorTouch)
#pragma config(Sensor, dgtl5,  limitSwitchBottom, sensorTouch)
#pragma config(Motor,  port1,           collector,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           laucher,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 50;//threshold value
	//x drive base
	while(true)
	{
		if(abs(vexRT[Ch2]) < threshold)
		{
			motor[frontRight] = 0;
			motor[backRight] = 0;
		}
		else
		{
			motor[frontRight] = vexRT[Ch2];
			motor[backRight] = vexRT[Ch2];
		}

		if(abs(vexRT[Ch3]) < threshold)
		{
			motor[frontLeft] = 0;
			motor[backLeft] = 0;
		}
		else
		{
			motor[frontLeft] = vexRT[Ch3];
			motor[backLeft] = vexRT[Ch3];
		}

		//Strafing
		while(vexRT[Btn6U] == 1)
		{
			motor[frontLeft] = 127;
			motor[frontRight] = -127;
			motor[backLeft] = -127;
			motor[backRight] = 127;
		}

		while(vexRT[Btn5U] == 1)
		{
			motor[frontLeft] = -127;
			motor[frontRight] = 127;
			motor[backLeft] = 127;
			motor[backRight] = -127;
		}

		//collector
		if(vexRT[Btn6UXmtr2] == 1)
		{
			while(SensorValue[limitSwitchTop] != 1)
			{
				motor[collector] = 127;
			}

			while(SensorValue[limitSwitchBottom] != 1)
			{
				motor[collector] = -127;
			}
			motor[collector] = 0;
		}

		//lift
		if(abs(vexRT[Ch3Xmtr2]) < threshold)
		{
			motor[liftLeft] = 0;
			motor[liftRight] = 0;
		}
		else
		{
			motor[liftLeft] = vexRT[Ch3Xmtr2];
			motor[liftRight] = vexRT[Ch3Xmtr2];
		}

		//laucher
		while(vexRT[Btn5DXmtr2] == 1)
		{
			motor[laucher] = 127;
		}
	}
}
