#pragma config(Sensor, dgtl3,  limitSwitchTop, sensorTouch)
#pragma config(Sensor, dgtl5,  limitSwitchBottom, sensorTouch)
#pragma config(Motor,  port1,           collector,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           laucher,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold(int number, int threshold = 50)
{
	/*  Returns a value constrained to a threshold defined by the optional threshold parameter to this function, or 50 if no value is passed */
	return (abs(number) <= threshold) ?  0 : number;
}

task main()
{
	// X drive base
	while(true)
	{
		motor[frontRight] = threshold(vexRT[Ch2]);
		motor[backRight] = threshold(vexRT[Ch2]);

		motor[frontLeft] = threshold(vexRT[Ch3]);
		motor[backLeft] = threshold(vexRT[Ch3]);

		// Strafing
		if (vexRT[Btn6U] == 1) {
			while(vexRT[Btn6U] == 1)
			{
				motor[frontLeft] = motor[backRight] = 127;
				motor[frontRight] = motor[backLeft] = -127;
			}
			motor[frontLeft] = motor[backRight] = motor[frontRight] = motor[backLeft] = 0;
		}
		if (vexRT[Btn5U] == 1)
		{
			while(vexRT[Btn5U] == 1)
			{
				motor[frontLeft] = motor[backRight] = -127;
				motor[frontRight] = motor[backLeft] = 127;
			}
			motor[frontLeft] = motor[backRight] = motor[frontRight] = motor[backLeft] = 0;
		}

		// Collector
		if(vexRT[Btn6UXmtr2] == 1)
		{
			while(SensorValue[limitSwitchTop] != 1)
			{
				motor[collector] = 127;
			}

			while(SensorValue[limitSwitchBottom] != 1)
			{
				motor[collector] = -127;
			}
			motor[collector] = 0;
		}

		//lift
		motor[liftLeft] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftRight] = threshold(vexRT[Ch3Xmtr2]);

		//laucher
		while(vexRT[Btn5DXmtr2] == 1)
		{
			motor[laucher] = 127;
		}
	}
}
