#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float timewait = 0;
bool running = true;

task main()
{
	while(running == true)
	{
		while(timewait < 333333)
		{
			if(vexRT[Btn7L] == 1)
			{
				timewait = 1000000;
			}
			else if(vexRT[Btn7U] == 1)
			{
				timewait = 2000000;
			}
			else if(vexRT[Btn7R] == 1)
			{
				timewait = 3000000;
			}
			timewait++;
		}

		if(timewait == 333333)
		{
			motor[servo] = 70;
			wait1Msec(500);
			motor[servo] = 0;
			while(true)
			{
				motor[motor2] = vexRT[Ch3];
				motor[motor1] = vexRT[Ch2];
				motor[motor4] = vexRT[Ch3Xmtr2];
				motor[motor3] = vexRT[Ch2Xmtr2];
				if(vexRT[Btn8U] == 1)
				{
					timewait = 2000000;
					break;
				}
				else if(vexRT[Btn8R] == 1)
				{
					timewait = 3000000;
					break;
				}
				else if(SensorValue[bumper] == 1)
				{
					running = false;
					break;
				}
			}
		}
		else if(timewait >= 1000000 && timewait <= 1000100)
		{
			motor[servo] = 70;
			wait1Msec(500);
			motor[servo] = 0;
			while(true)
			{
				motor[motor2] = vexRT[Ch3];
				motor[motor1] = vexRT[Ch2];
				motor[motor4] = vexRT[Ch3Xmtr2];
				motor[motor3] = vexRT[Ch2Xmtr2];
				if(vexRT[Btn8U] == 1)
				{
					timewait = 2000000;
					break;
				}
				else if(vexRT[Btn8R] == 1)
				{
					timewait = 3000000;
					break;
				}
				else if(SensorValue[bumper] == 1)
				{
					running = false;
					break;
				}
			}
		}
		else if(timewait >= 2000000 && timewait <= 2000100)
		{
			motor[servo] = 70;
			wait1Msec(1000);
			motor[servo] = 0;
			while(true)
			{
				motor[motor3] = vexRT[Ch3];
				motor[motor4] = vexRT[Ch3];
				motor[motor1] = vexRT[Ch2];
				motor[motor2] = vexRT[Ch2];
				if(vexRT[Btn8L] == 1)
				{
					timewait = 1000000;
					break;
				}
				else if(vexRT[Btn8R] == 1)
				{
					timewait = 3000000;
					break;
				}
				else if(SensorValue[bumper] == 1)
				{
					running = false;
					break;
				}
			}
		}
		else if(timewait >= 3000000 && timewait <= 3000100)
		{
			motor[servo] = 70;
			wait1Msec(1500);
			motor[servo] = 0;
			while(true)
			{
				motor[motor2] = vexRT[Ch3];
				motor[motor1] = vexRT[Ch2];
				motor[motor3] = vexRT[Ch3Xmtr2];
				motor[motor4] = vexRT[Ch3Xmtr2];
				if(vexRT[Btn8L] == 1)
				{
					timewait = 1000000;
					break;
				}
				else if(vexRT[Btn8U] == 1)
				{
					timewait = 2000000;
					break;
				}
				else if(SensorValue[bumper] == 1)
				{
					running = false;
					break;
				}
			}
		}
	}
}
