#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  leftMotorEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float fullcycle = 392; //The value of the encoder will be about this number

task main()
{
  SensorValue[leftMotorEncoder] = 0;
	while(SensorValue[leftMotorEncoder] < 3*fullcycle)
	{
		motor[leftMotor] = 75;
	}
	motor[leftMotor] = -10;
	wait1Msec(1000);
	motor[leftMotor] = 0;
}
