#pragma config(Motor,  port1,           RightRearMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftRearMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightFrontMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftSlideMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightSlideMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           KickerArmMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           KickerMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int STOP = 0 ;

void MoveDirection(int LeftSpeed, int RightSpeed, int duration)
{
	motor[RightFrontMotor] = RightSpeed ;
	motor[RightRearMotor] = RightSpeed ;
	motor[LeftFrontMotor] = LeftSpeed ;
	motor[LeftRearMotor] = LeftSpeed ;

	wait1Msec(duration) ;

	motor[RightFrontMotor] = STOP ;
	motor[RightRearMotor] = STOP ;
	motor[LeftFrontMotor] = STOP ;
	motor[LeftRearMotor] = STOP ;
}


void Collect(int duration)
{
	//motor[KickerArmMotor] = -127 ;
	motor[KickerMotor] = 127 ;

	wait1Msec(duration) ;

	motor[KickerArmMotor] = STOP ;
	motor[KickerMotor] = STOP ;
}



task main()
{
		//MoveForward(127, 1200) ; //Move to line

		//Collect(400) ; //Prep for collection

		//Turn(STOP, 127, 2100) ; //Turn towards star

		//MoveForward(90, 500) ; //Move onto stars

		//motor[KickerMotor] = -127 ;

		//wait1Msec(500) ;

		//motor[KickerArmMotor] = -127 ;

		//wait1Msec(1000) ;

	MoveDirection(127, -127, 2250) ; //Make a full 180 so the slider is pointed towards the stars on the fence

	MoveDirection(-127, -127, 2200) ; //Move towards the stars on the fence

		motor[RightSlideMotor] = 127 ; //Boop the stars off the fence
		motor[LeftSlideMotor] = 127 ;

		wait1Msec(1000) ;

		motor[RightSlideMotor] = -127 ; //Pull the sliders back
		motor[LeftSlideMotor] = -127 ;

	MoveDirection(127, 127, 500) ; //Pull away from the fence

		motor[RightSlideMotor] = STOP ;
		motor[LeftSlideMotor] = STOP ;

	MoveDirection(127, -127, 1125) ; // Turn for the next star

	MoveDirection(-100, -100, 600) ; //Move forward for next star

	MoveDirection(-127, 127, 1127) ; //Spin towards stars on fence again

	MoveDirection(-127, -127, 500) ;

		motor[RightSlideMotor] = 127 ; //Boop the stars off the fence
		motor[LeftSlideMotor] = 127 ;

		wait1Msec(1000) ;

		motor[RightSlideMotor] = -127 ; //Pull the sliders back
		motor[LeftSlideMotor] = -127 ;



} //task main()
