#pragma config(Sensor, dgtl1,  collectorLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  catapultLimitSwitch, sensorTouch)
#pragma config(Motor,  port1,           collector1,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           launcher1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           launcher2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          collector2,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold(int number, int threshold = 50)
{// Returns a value constrained to a threshold defined by the optional threshold parameter to this function, or 50 if no value is
	return (abs(number) <= threshold) ? 0 : number;
}
task main()
{
	//x drive base
	while(true)
	{
		motor[frontRight] = threshold(vexRT[Ch2]);
		motor[backRight] = threshold(vexRT[Ch2]);
		motor[frontLeft] = threshold(vexRT[Ch3]);
		motor[backLeft] = threshold(vexRT[Ch3]);

		//Strafing
		while(vexRT[Btn6U] == 1)
		{
			motor[frontLeft] = 127;
			motor[frontRight] = -127;
			motor[backLeft] = -127;
			motor[backRight] = 127;
		}

		while(vexRT[Btn5U] == 1)
		{
			motor[frontLeft] = -127;
			motor[frontRight] = 127;
			motor[backLeft] = 127;
			motor[backRight] = -127;
		}

		//collector
		if(threshold(vexRT[Ch3Xmtr2]) > 0)
		{
			while(SensorValue[collectorLimitSwitch] != 1)
			{
				motor[collector1] = 127;
				motor[collector2] = 127;
			}
			motor[collector1] = 0;
			motor[collector2] = 0;
		}
		else if (threshold(vexRT[Ch3Xmtr2]) < 0)
		{
			motor[collector1] = motor[collector2] = -127;
		}
		else
		{
			motor[collector1] = motor[collector2] = 0;
		}

		//lift
		if(vexRT[Btn5UXmtr2] == 1)
		{
			motor[liftLeft] = 127;
			motor[liftRight] = 127;
		}
		else if (vexRT[Btn5DXmtr2] == 1)
		{
			motor[liftLeft] = -127;
			motor[liftRight] = -127;
		}
		else
		{
			motor[liftLeft] = 0;
			motor[liftRight] = 0;
		}

		// Catapult code
		if(vexRT[Btn8DXmtr2] == 1)
		{
			while(SensorValue[catapultLimitSwitch] != 1)
			{
				motor[launcher1] = 127;
				motor[launcher2] = 127;
			}
			motor[launcher1] = 0;
			motor[launcher2] = 0;
		}

		if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[launcher1] = 127;
			motor[launcher2] = 127;
		}
		else
		{
			motor[launcher1] = 0;
			motor[launcher2] = 0;
		}
	}
}
