#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  leftBumper,     sensorTouch)
#pragma config(Sensor, dgtl2,  rightBumper,    sensorTouch)
#pragma config(Sensor, I2C_1,  backLeftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  liftLeft1Encoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  liftRight1Encoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  backRightEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftLeft1,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port4,           collectorRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeft2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight1,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port7,           collectorLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftRight2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "LCD_Setup.c"
#include "Autonomous_Functions.c"

/*---------------------------Autonmous program starts here------------------------------*/
float fullcycle = 392;
task autonomous()
{
	switch(autonNumber) {
	case 0://First Autonomous
		clearLCDLine(0);
		displayLCDCenteredString(0, "Auton 1 Selected");
		//threestar(55, 55, -50, 1550);
		//wait1Msec(100);
		//threestar(0, 0, 0, 1);
		lift(100, 1150);
		wait1Msec(100);
		claw(-127, 800);
		wait1Msec(100);
		base(50, 50, 3000);
		wait1Msec(200);
		base(-100, -100, 250);
		wait1Msec(500);
		break;
	case 1://Second Autonomous
		clearLCDLine(0);
		displayLCDCenteredString(0, "Auton 2 Selected");
		lift(100, 1150);
		wait1Msec(100);
		claw(-127, 800);
		wait1Msec(100);
		base(127, 127, 1300);
		wait1Msec(200);
		base(-127, -127, 700);
		wait1Msec(100);
		base(-127, 127, 500);
		wait1Msec(100);
		lift(-100, 1000);
		wait1Msec(100);
		base(127, 127, 700);
		wait1Msec(100);
		claw(127, 900);//holding
		holding(50, 127, 700);
		base(127, 127, 500);//new code
		base(127, -127, 550);
		wait1Msec(100);
		base(127, 127, 1200);
		wait1Msec(100);
		claw(-127, 500);
		wait1Msec(100);
		base(-127, -127, 500);
		wait1Msec(100);
		lift(-100, 400);
		claw(-127, 300);
		base(127, 127, 1000);
		break;
	case 2://Third Autonomous
		clearLCDLine(0);
		displayLCDCenteredString(0, "Auton 3 Selected");
		lift(100, 1150);
		wait1Msec(100);
		claw(-127, 800);
		wait1Msec(100);
		base(127, 127, 1300);
		wait1Msec(200);
		base(-127, -127, 600);
		wait1Msec(100);
		base(127, -127, 500);
		wait1Msec(100);
		lift(-100, 1000);
		wait1Msec(100);
		base(127, 127, 700);
		wait1Msec(100);
		claw(127, 900);//holding
		holding(50, 127, 700);
		base(127, 127, 500);//new code
		base(-127, 127, 550);
		wait1Msec(100);
		base(127, 127, 1200);
		wait1Msec(100);
		claw(-127, 500);
		wait1Msec(100);
		base(-127, -127, 500);
		wait1Msec(100);
		lift(-100, 400);
		claw(-127, 300);
		base(127, 127, 1000);
		break;
	case 3:
		clearLCDLine(0);
		displayLCDCenteredString(0, "Auton 4 Selected");
		/*-------------------Encoder Testing Code----------------*/
		SensorValue[liftLeft1Encoder] = 0;
		while(abs(SensorValue[liftLeft1Encoder]) < 2.2*fullcycle)//while lift encoder value is less than 2.2 fullcycle
		{
			liftEncoder(127);
		}
		liftEncoder(0);
		claw(-127, 900);
		while(SensorValue[leftBumper] == 0 || SensorValue[rightBumper] == 0)//if left bumper or right bumper are not press run the following loop
		{
			if(SensorValue[leftBumper] == 0 && SensorValue[rightBumper] == 0)//if both bumper are not press
			{
				baseEncoder(127, 127);
			}
			else if(SensorValue[leftBumper] == 1 && SensorValue[rightBumper] == 0)//if left bumper is press
			{
				baseEncoder(0, 127);
			}
			else if(SensorValue[leftBumper] == 0 && SensorValue[rightBumper] == 1)//if right bumper is press
			{
				baseEncoder(127, 0);
			}
			else//if nothing above happen
			{
				baseEncoder(0, 0);
			}
		}//end of the loop
		baseEncoder(0, 0);
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 0.3*fullcycle)//while base encoder value is less than 5 fullcycle
		{
			baseEncoder(-127, -127);//move backwards
		}
		baseEncoder(0, 0);
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 3*fullcycle)//while base encoder value is less than 3 fullcycle
		{
			baseEncoder(-127, 127);//turn left
		}
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 4*fullcycle)//while base encoder value is less than 4 fullcycle
		{
			baseEncoder(127, 127);//move forward
		}
		SensorValue[liftLeft1Encoder] = 0;//clear encoder value
		while(abs(SensorValue[liftLeft1Encoder]) < 5*fullcycle)//while lift encoder value is less than 5 fullcycle
		{
			holdingEncoder(127, 127);//collect the cube and lift at the same time
		}
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 3*fullcycle)//while base encoder value is less than 3 fullcycle
		{
			baseEncoder(127, -127);//turn right
		}
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 3*fullcycle)//while base encoder value is less than 3 fullcycle
		{
			baseEncoder(127, 127);//move forward
		}
		claw(-127, 700);//open the claw to drop the cube
		break;
	case 4://autonomous 5
		clearLCDLine(0);
		displayLCDCenteredString(0, "Auton 4 Selected");
		SensorValue[liftLeft1Encoder] = 0;
		while(abs(SensorValue[liftLeft1Encoder]) < 2.2*fullcycle)//while lift encoder value is less than 2.2 fullcycle
		{
			liftEncoder(127);
		}
		liftEncoder(0);
		claw(-127, 900);
		while(SensorValue[leftBumper] == 0 || SensorValue[rightBumper] == 0)//if left bumper or right bumper are not press run the following loop
		{
			if(SensorValue[leftBumper] == 0 && SensorValue[rightBumper] == 0)//if both bumper are not press
			{
				baseEncoder(127, 127);
			}
			else if(SensorValue[leftBumper] == 1 && SensorValue[rightBumper] == 0)//if left bumper is press
			{
				baseEncoder(0, 127);
			}
			else if(SensorValue[leftBumper] == 0 && SensorValue[rightBumper] == 1)//if right bumper is press
			{
				baseEncoder(127, 0);
			}
			else//if nothing above happen
			{
				baseEncoder(0, 0);
			}
		}//end of the loop
		baseEncoder(0, 0);
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 0.3*fullcycle)//while base encoder value is less than 5 fullcycle
		{
			baseEncoder(-127, -127);//move backwards
		}
		baseEncoder(0, 0);
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 3*fullcycle)//while base encoder value is less than 3 fullcycle
		{
			baseEncoder(-127, 127);//turn left
		}
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 4*fullcycle)//while base encoder value is less than 4 fullcycle
		{
			baseEncoder(127, 127);//move forward
		}
		SensorValue[liftLeft1Encoder] = 0;//clear encoder value
		while(abs(SensorValue[liftLeft1Encoder]) < 5*fullcycle)//while lift encoder value is less than 5 fullcycle
		{
			holdingEncoder(127, 127);//collect the cube and lift at the same time
		}
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 3*fullcycle)//while base encoder value is less than 3 fullcycle
		{
			baseEncoder(127, -127);//turn right
		}
		SensorValue[backLeftEncoder] = 0;//clear encoder value
		while(abs(SensorValue[backLeftEncoder]) < 3*fullcycle)//while base encoder value is less than 3 fullcycle
		{
			baseEncoder(127, 127);//move forward
		}
		claw(-127, 700);//open the claw to drop the cube
		break;
	case 5:
		clearLCDLine(0);
		displayLCDCenteredString(0, "Auton 5 Selected");
		SensorValue[liftLeft1Encoder] = 0;
		while(abs(SensorValue[liftLeft1Encoder]) < 2.2*fullcycle)//while lift encoder value is less than 2.2 fullcycle
		{
			liftEncoder(127);
		}
		liftEncoder(0);
		claw(-127, 900);
		while(SensorValue[leftBumper] == 0 || SensorValue[rightBumper] == 0)//if left bumper or right bumper are not press run the following loop
		{
			if(SensorValue[leftBumper] == 0 && SensorValue[rightBumper] == 0)//if both bumper are not press
			{
				baseEncoder(127, 127);
			}
			else if(SensorValue[leftBumper] == 1 && SensorValue[rightBumper] == 0)//if left bumper is press
			{
				baseEncoder(0, 127);
			}
			else if(SensorValue[leftBumper] == 0 && SensorValue[rightBumper] == 1)//if right bumper is press
			{
				baseEncoder(127, 0);
			}
			else//if nothing above happen
			{
				baseEncoder(0, 0);
			}
		}//end of the loop
		baseEncoder(0, 0);
	}
	AutonomousCodePlaceholderForTesting();
}
/*-----------------------------Autonomouse ends here----------------------------------*/

/*---------------------------Driver control starts here-------------------------------*/
int threshold(int number, int threshold = 50)
{// Returns a value constrained to a threshold defined by the optional threshold parameter to this function, or 50 if no value is
	return (abs(number) <= threshold) ? 0 : number;
}
task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
		//lift
		motor[liftLeft1] = threshold(vexRT[Ch3Xmtr2]);//Ch3: all four motors run at the same time
		motor[liftRight1] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftLeft2] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftRight2] = threshold(vexRT[Ch3Xmtr2]);

		//if(vexRT[Btn7LXmtr2] == 1)
		//{
		//	SensorValue[liftRight1] = 0;
		//	while(SensorValue[liftRight1] < 3*fullcycle)
		//	{
		//		liftEncoder(127);
		//	}
		//}
		//else if(vexRT[Btn7DXmtr2] == 1)
		//{
		//	SensorValue[liftRight1] = 0;
		//	while(SensorValue[liftRight1] <4*fullcycle)
		//	{
		//		liftEncoder(127);
		//	}
		//}
		//else
		//{
		//	motor[liftLeft1] = threshold(vexRT[Ch3Xmtr2]);//Ch3: all four motors run at the same time
		//	motor[liftRight1] = threshold(vexRT[Ch3Xmtr2]);
		//	motor[liftLeft2] = threshold(vexRT[Ch3Xmtr2]);
		//	motor[liftRight2] = threshold(vexRT[Ch3Xmtr2]);
		//}
		//collector
		if(vexRT[Btn6UXmtr2] == 1)//if button 6U is pressed
		{
			motor[collectorLeft] = 127;//open the claw
			motor[collectorRight] = 127;
		}
		else if(vexRT[Btn6DXmtr2] == 1)//if button 6D is pressed
		{
			motor[collectorLeft] = -127;//close the claw
			motor[collectorRight] = -127;
		}
		else//if nothing is pressed, run the folowing program
		{
			motor[collectorLeft] = 0;//stop the claw
			motor[collectorRight] = 0;
		}
		//base
		//Gio's control
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];//Ch3: move all six motors on the base forward or backwards
		motor[backRight] = vexRT[Ch3] - vexRT[Ch1];//Ch1: make the base turn left or right
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];//Ch3 and Ch1: one side disable, another side can still turn
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1];

		//motor[backLeft] = vexRT[Ch3];
		//motor[backRight] = vexRT[Ch2];
		//motor[frontLeft] = vexRT[Ch3];
		//motor[frontRight] = vexRT[Ch2];
		UserControlCodePlaceholderForTesting();
	}
}
