#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftLeft1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           collectorRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeft2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           collectorLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRight2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int autonNumber = 0;

//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

void pre_auton()
{
	bStopTasksBetweenModes = true;
	/*------------------------LCD Program Start Here--------------------------*/
	bLCDBacklight = true;                                    // Turn on LCD Backlight
	string mainBattery, backupBattery;
	clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
	clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
	displayNextLCDString(backupBattery);

	//Short delay for the LCD refresh rate
	wait1Msec(2000);

	//Declare count variable to keep track of our choice
	int count = 0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count)
		{
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Autonomous 1");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
				} else if(nLCDButtons == centerButton) {
				startTask(usercontrol);
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Autonomous 2");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
				} else if(nLCDButtons == centerButton) {
				autonNumber = 0;
				startTask(autonomous);
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Autonomous 3");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
				} else if(nLCDButtons == centerButton) {
				autonNumber = 1;
				startTask(autonomous);
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Autonomous 4");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
				} else if(nLCDButtons == centerButton) {
				autonNumber = 2;
				startTask(autonomous);
			}
			break;
		default:
			count = 0;
			break;
		}
	}
}
/*---------------------------Autonmous program starts here------------------------------*/
void base(int left, int right, int time)//base function for autonomous
{
	motor[backLeft] = left;
	motor[backRight] = right;
	motor[frontLeft] = left;
	motor[frontRight] = right;
	wait1Msec(time);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
}

void lift(int speed, int time)//lift function
{
	motor[liftLeft1] = speed;
	motor[liftLeft2] = speed;
	motor[liftRight1] = speed;
	motor[liftRight2] = speed;
	wait1Msec(time);
	motor[liftLeft1] = 0;
	motor[liftLeft2] = 0;
	motor[liftRight1] = 0;
	motor[liftRight2] = 0;
}

void claw(int speed, int time)//claw function
{
	motor[collectorLeft] = speed;
	motor[collectorRight] = speed;
	wait1Msec(time);
	motor[collectorLeft] = 0;
	motor[collectorRight] = 0;
}

task autonomous()
{
	switch(autonNumber) {
	case 0://First Autonomous
		while(true)
		{
			clearLCDLine(0);
			displayLCDCenteredString(0, "Auton 1 Selected");
			lift(100, 100);
			claw(127, 100);
			lift(100, 1200);
			claw(127, 200);
			base(127, 127, 2000);
			base(0, 0, 500);
			//base(-127, -127, 700);
			//lift(100, 1100);
			//base(127, -127, 500);
			//base(127, 127, 700);
			//claw(127, 500);
			//lift(127, 1000);
			//base(127, 127, 500);
			//claw(-127, 500);
		}
		break;
	case 1://Second Autonomous
		while(true)
		{
			clearLCDLine(0);
			displayLCDCenteredString(0, "Auton 2 Selected");
		}
		break;
	case 2://Third Autonomous
		while(true)
		{
			clearLCDLine(0);
			displayLCDCenteredString(0, "Auton 3 Selected");
		}
		break;
	case 3:
		while(true)
		{
			clearLCDLine(0);
			displayLCDCenteredString(0, "Auton 4 Selected");
		}
	}
	AutonomousCodePlaceholderForTesting();
}
/*-----------------------------Autonomouse ends here----------------------------------*/

/*---------------------------Driver control starts here-------------------------------*/
int threshold(int number, int threshold = 50)
{// Returns a value constrained to a threshold defined by the optional threshold parameter to this function, or 50 if no value is
	return (abs(number) <= threshold) ? 0 : number;
}
task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
		//lift
		motor[liftLeft1] = threshold(vexRT[Ch3Xmtr2]);//Ch3: all four motors run at the same time
		motor[liftRight1] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftLeft2] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftRight2] = threshold(vexRT[Ch3Xmtr2]);
		//collector
		if(vexRT[Btn6UXmtr2] == 1)//if button 8U is pressed
		{
			motor[collectorLeft] = 127;//open the claw
			motor[collectorRight] = 127;
		}
		else if(vexRT[Btn6DXmtr2] == 1)//if button 8D is pressed
		{
			motor[collectorLeft] = -127;//close the claw
			motor[collectorRight] = -127;
		}
		else//if nothing is pressed, run the folowing program
		{
			motor[collectorLeft] = 0;//stop the claw
			motor[collectorRight] = 0;
		}
		//base
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];//Ch3: move all six motors on the base forward or backwards
		motor[backRight] = vexRT[Ch3] - vexRT[Ch1];//Ch1: make the base turn left or right
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];//Ch3/Ch1: one side disable, another side can still turn
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1];
		UserControlCodePlaceholderForTesting();
	}
}
