#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftLeft1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           collectorRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeft2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRight1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           collectorLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftRight2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}
/*---------------------------Autonmous program starts here------------------------------*/
void base(int left, int right, int time)//base function for autonomous
{
	motor[backLeft] = left;
	motor[backRight] = right;
	motor[frontLeft] = left;
	motor[frontRight] = right;
	wait1Msec(time);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
}

void lift(int speed, int time)//lift function
{
	motor[liftLeft1] = speed;
	motor[liftLeft2] = speed;
	motor[liftRight1] = speed;
	motor[liftRight2] = speed;
	wait1Msec(time);
	motor[liftLeft1] = 0;
	motor[liftLeft2] = 0;
	motor[liftRight1] = 0;
	motor[liftRight2] = 0;
}

void claw(int speed, int time)//claw function
{
	motor[collectorLeft] = speed;
	motor[collectorRight] = speed;
	wait1Msec(time);
	motor[collectorLeft] = 0;
	motor[collectorRight] = 0;
}

task autonomous()
{
	lift(100, 100);
	claw(127, 100);
	lift(100, 1200);
	claw(127, 200);
	base(127, 127, 2000);
	base(0, 0, 500);
	//base(-127, -127, 700);
	//claw(-127, 700);
	//base(-127, -127, 500);
	//base(0, 0, 500);
	//claw(127, 1000);
	//base(127, 127, 800);
	//base(0, 0, 500);
}
/*-----------------------------Autonomouse ends here----------------------------------*/

/*---------------------------Driver control starts here-------------------------------*/
int threshold(int number, int threshold = 50)
{// Returns a value constrained to a threshold defined by the optional threshold parameter to this function, or 50 if no value is
	return (abs(number) <= threshold) ? 0 : number;
}
task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
		//lift
		motor[liftLeft1] = threshold(vexRT[Ch3Xmtr2]);//Ch3: all four motors run at the same time
		motor[liftRight1] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftLeft2] = threshold(vexRT[Ch3Xmtr2]);
		motor[liftRight2] = threshold(vexRT[Ch3Xmtr2]);
		//collector
		if(vexRT[Btn8UXmtr2] == 1)//if button 8U is pressed
		{
			motor[collectorLeft] = 127;//open the claw
			motor[collectorRight] = 127;
		}
		else if(vexRT[Btn8DXmtr2] == 1)//if button 8D is pressed
		{
			motor[collectorLeft] = -127;//close the claw
			motor[collectorRight] = -127;
		}
		else//if nothing is pressed, run the folowing program
		{
				if(vexRT[Btn5UXmtr2] == 1)//if button 5U is pressed
				{
					motor[collectorLeft] = 127;//left collector open
				}
				else if(vexRT[Btn5DXmtr2] == 1)//if button 5D is pressed
				{
					motor[collectorLeft] = -127;//left collector close
				}
				else//if nothing is pressed
				{
					motor[collectorLeft] = 0;//stop left collector
				}

				if(vexRT[Btn6UXmtr2] == 1)//if button 6U is pressed
				{
					motor[collectorRight] = 127;//collector right open
				}
				else if (vexRT[Btn6DXmtr2] == 1)//if button 6D is pressed
				{
					motor[collectorRight] = -127;//collector right close
				}
				else//if nothing is press
				{
					motor[collectorRight] = 0;//stop right collector
				}
		}
		//base
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];//Ch3: move all six motors on the base forward or backwards
		motor[backRight] = vexRT[Ch3] - vexRT[Ch1];//Ch1: make the base turn left or right
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];//Ch3/Ch1: one side disable, another side can still turn
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1];
    UserControlCodePlaceholderForTesting();
  }
}
