#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftLeft1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           collectorLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftLeft2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftRight1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           collectorRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRight2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{	//lift
		motor[liftLeft1] = vexRT[Ch3];
		motor[liftRight1] = vexRT[Ch3];
		motor[liftLeft2] = vexRT[Ch3];
		motor[liftRight2] = vexRT[Ch3];

		//collector
		if(vexRT[Btn6U] == 1)
		{
			motor[collectorRight] = 127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[collectorRight] = -127;
		}
		else
		{
			motor[collectorRight] = 0;
		}

		if(vexRT[Btn5UXmtr2] == 1)
		{
			motor[collectorLeft] = 127;
		}
		else if(vexRT[Btn5DXmtr2] == 1)
		{
			motor[collectorLeft] = 127;
		}
		else
		{
			motor[collectorLeft] = 0;
		}
		//base
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[backRight] = vexRT[Ch3] - vexRT[Ch1];
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1];
	}
}
